name: Android SDK & NDK Setup with TDLib Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tdlib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34  # Adjust according to your project requirements
        build-tools-version: 34.0.0
        ndk-version: 27.0.0  # Specify the NDK version

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gperf php

    - name: Set up SDK in TDLib directory
      run: |
        mkdir -p td/example/android/SDK
        rsync -av $ANDROID_HOME/ td/example/android/SDK/
        mkdir -p td/example/android/SDK/ndk
        rsync -av $ANDROID_NDK_HOME/ td/example/android/SDK/ndk/

    - name: Build TDLib for Android
      run: |
        cd td/example/android/
        ./build-tdlib.sh

    - name: Zip the TDLib Android folder
      run: |
        cd td/example/android/
        zip -r tdlib-android.zip ./

    - name: Upload the artifact
      uses: actions/upload-artifact@v3
      with:
        name: tdlib-android
        path: td/example/android/tdlib-android.zip
