name: Build TdLib for android libtdjni

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tdlib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'  
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gperf php
        
    - name: Download TDLib
      run: |
        git clone https://github.com/tdlib/td.git
    
    - name: Build TDLib for Android libtdjni
      run: |
        cd td/example/android/
        chmod +x *
        ./check-environment.sh
        ./fetch-sdk.sh
        ./build-openssl.sh
        ./build-tdlib.sh

    - name: Upload the artifact
      uses: actions/upload-artifact@v3
      with:
        name: tdlib
        path: td/example/android/tdlib/tdlib.zip
        
