name: Android SDK & NDK Setup with TDLib Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tdlib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK and NDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools-version: 34.0.0
        ndk-version: 27.0.0

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gperf php

    - name: Copy SDK and NDK to TDLib
      run: |
        mkdir -p td/example/android/android-sdk
        mkdir -p td/example/android/android-ndk
        cp -r $ANDROID_HOME/* td/example/android/android-sdk/
        cp -r $ANDROID_NDK_HOME/* td/example/android/android-ndk/

    - name: Print environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME"
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"

    - name: Download TDLib
      run: |
        git clone https://github.com/tdlib/td.git

    - name: Build TDLib for Android
      run: |
        cd td/example/android/
        ./build-tdlib.sh

    - name: Zip the TDLib Android folder
      run: |
        cd td/example/android/
        zip -r tdlib-android.zip ./

    - name: Upload the artifact
      uses: actions/upload-artifact@v3
      with:
        name: tdlib-android
        path: td/example/android/tdlib-android.zip
